### PR TITLE
Feat: Add Fallback PNGs for inline SVGs.

### LINKED ISSUE #143: Add backup images for non SVG devices
slack_for_ios_upload_720

- SVGs do not load on Kindle Fire
- Kindle Fire with Kindle 6.3.1

### PR DESCRIPTION
**Pull request by catheraaine**
- Needs tested on non-svg devices.

closes #143

### CODE REVIEW

**Comment by catheraaine** [comment]
Fixed the link urls! This should be good to go now! 

@iAmNathanJ @BC3209 @boomingbrake

**Comment by iAmNathanJ** [comment]
@catheraaine This was tested on non svg device? Or do we need to do that?

**Comment by catheraaine** [comment]
This. Hurts. That Logo. I'm not sure. 

img_5038

**Comment by iAmNathanJ** [comment]
@catherine is this the Silk browser?

**Comment by Catherine** [comment]
whoops, wrong Catherine you just pinged in the comment @iAmNathanJ.

**Comment by iAmNathanJ** [comment]
@catheraaine  is this the Silk browser?

**Comment by boomingbrake** [comment]
YAY!!!

**Pull request merged**
