### PR TITLE
Docs upgrade

### PR DESCRIPTION
**Pull request by iAmNathanJ**
Lots of changes here. @catheraaine I opened #269 regarding some of the challenges here. 
I would love some feedback and help if you're able.

### CODE REVIEW

**Comment by catheraaine** [comment]
* I feel like Circle CI / Code Climate badges should still be at the top of the Dev block. Even if the descriptions are lower down. 

* Did you turn _about into partials? Is that what that was?

**Comment by catheraaine** [comment]
It sounds awesome, overall!!

**Comment by iAmNathanJ** [comment]
@catheraaine made that change, but this is still WIP. See #269

**Comment by iAmNathanJ** [comment]
@catheraaine since this is now a big job, I'm gonna create another branch and pr with the intermediate changes for now. Keep this open for the time being. 😄

**Pull request merged**
